const {app,BrowserWindow,dialog,ipcMain}=require('electron');
const {autoUpdater}=require('electron-updater');
const {spawn}=require('child_process');
const fs=require('fs');const http=require('http');const path=require('path');
let win,backend,port;const packaged=app.isPackaged;const root=packaged?process.resourcesPath:path.resolve(__dirname,'../../..');
function freePort(){return new Promise((ok,no)=>{const s=http.createServer();s.on('error',no);s.listen(0,'127.0.0.1',()=>{const p=s.address().port;s.close(()=>ok(p));});});}
function waitReady(p){return new Promise((ok,no)=>{const begin=Date.now(),probe=()=>{const r=http.get(`http://127.0.0.1:${p}/api/state`,x=>{x.resume();if(x.statusCode===200)return ok();retry();});r.on('error',retry);r.setTimeout(1000,()=>{r.destroy();retry();});},retry=()=>Date.now()-begin>30000?no(new Error('模拟服务启动超时')):setTimeout(probe,250);probe();});}
async function startBackend(){port=await freePort();const exe=path.join(process.resourcesPath,'backend','cyberarm-backend.exe');const env={...process.env,CYBERARM_PORT:String(port),CYBERARM_RESOURCE_DIR:packaged?process.resourcesPath:path.join(root,'simulator'),CYBERARM_WORKSPACE_DIR:app.getPath('userData'),PYTHONPATH:packaged?undefined:path.join(root,'simulator/backend')};backend=spawn(packaged?exe:process.env.CYBERARM_PYTHON||'python',packaged?[]:['-m','uvicorn','cyberarm.server:app'],{env,windowsHide:true,stdio:['ignore','pipe','pipe']});backend.stderr.on('data',x=>console.error(String(x)));backend.on('exit',code=>{if(!app.isQuitting&&code)dialog.showErrorBox('模拟服务退出',`退出码：${code}`);});await waitReady(port);}
function createWindow(){win=new BrowserWindow({width:1440,height:900,minWidth:1024,minHeight:720,backgroundColor:'#192736',title:'CyberArm Studio',webPreferences:{preload:path.join(__dirname,'preload.cjs'),contextIsolation:true,nodeIntegration:false}});win.loadURL(`http://127.0.0.1:${port}`);}
function setupUpdater(){autoUpdater.autoDownload=false;autoUpdater.autoInstallOnAppQuit=false;ipcMain.handle('update:check',async()=>{try{const r=await autoUpdater.checkForUpdates();return{available:Boolean(r?.updateInfo),version:r?.updateInfo?.version||null};}catch(e){return{available:false,error:e.message};}});ipcMain.handle('update:download',()=>autoUpdater.downloadUpdate());ipcMain.handle('update:install',()=>{if(backend&&!backend.killed)return{ok:false,reason:'请先停止模拟或真实机械臂'};autoUpdater.quitAndInstall();return{ok:true};});autoUpdater.on('update-downloaded',()=>win?.webContents.send('update:downloaded'));autoUpdater.on('download-progress',p=>win?.webContents.send('update:progress',p.percent));}
app.whenReady().then(async()=>{try{await startBackend();createWindow();setupUpdater();}catch(e){dialog.showErrorBox('CyberArm 启动失败',e.message);app.quit();}});app.on('before-quit',()=>{app.isQuitting=true;if(backend&&!backend.killed)backend.kill();});app.on('window-all-closed',()=>{if(process.platform!=='darwin')app.quit();});
