const {test,expect,_electron:electron}=require('@playwright/test');
const path=require('node:path');
const fs=require('node:fs');
const {pathToFileURL}=require('node:url');

test('浅色工作台：手动实时位置、预览开关、模式切换及小窗口布局',async()=>{
 const output=path.resolve(__dirname,'../test-results/manual-ui');fs.mkdirSync(output,{recursive:true});
 const env={...process.env,CYBERARM_TEST_USER_DATA:path.join(output,'user')};delete env.ELECTRON_RUN_AS_NODE;
 const packaged=process.env.CYBERARM_TEST_EXECUTABLE;
 const app=await electron.launch({...(packaged?{executablePath:packaged,args:[]}:{args:[path.resolve(__dirname,'..')]}),env});
 try{
  const page=await app.firstWindow();const errors=[];page.on('pageerror',e=>errors.push(e.message));
  let plans=0;page.on('request',r=>{if(r.url().endsWith('/api/plan'))plans++;});
  await expect(page.locator('.connection')).toContainText('本地已连接',{timeout:60000});
  await expect(page.locator('.scene-stage')).toHaveAttribute('data-model-status',/已载入/,{timeout:60000});
  await page.getByRole('button',{name:'实机',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'实机连接与校准'})).toContainText('未连接控制器');
  await expect(page.getByLabel('ESP32-S3 串口')).toBeVisible();
  await expect(page.getByRole('button',{name:'连接',exact:true})).toBeVisible();
  expect(await page.evaluate(()=>fetch('/api/hardware/ports').then(async r=>({status:r.status,data:await r.json()})))).toMatchObject({status:200,data:{ports:expect.any(Array)}});
  await page.screenshot({path:path.join(output,'hardware-panel.png')});
  await page.getByRole('button',{name:'关闭面板'}).click();
  const state=()=>page.evaluate(()=>fetch('/api/state').then(r=>r.json()));
  await expect(page.getByLabel('显示路径预览')).not.toBeChecked();
  await expect(page.getByRole('button',{name:'预览路径',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'关节',exact:true}).click();
  await page.getByLabel('底座旋转目标角度').fill('3');
  await expect.poll(async()=>(await state()).q_deg[0]).toBeCloseTo(3,2);
  await page.getByLabel('夹爪开合目标角度').fill('1');
  await expect.poll(async()=>(await state()).q_deg[5]).toBeCloseTo(1,2);
  expect(plans).toBe(0);
  await page.getByRole('button',{name:'末端',exact:true}).click();
  const initial=await state();
  const THREE=await import(pathToFileURL(path.resolve(__dirname,'../../simulator/frontend/node_modules/three/build/three.module.js')).href);
  const rect=await page.locator('.viewport canvas').boundingBox();
  const camera=new THREE.PerspectiveCamera(40,rect.width/rect.height,.001,10);camera.up.set(0,0,1);camera.position.set(.50,-.63,.38);camera.lookAt(.12,0,.115);camera.updateMatrixWorld();
  const tcp=new THREE.Vector3(...initial.tcp.slice(0,3).map(r=>r[3]));
  const point=tcp.clone().add(new THREE.Vector3(0,0,.035)).project(camera);
  const x=rect.x+(point.x+1)*rect.width/2,y=rect.y+(1-point.y)*rect.height/2;
  await page.mouse.move(x,y);await page.mouse.down();await page.mouse.move(x,y-9,{steps:8});
  await expect.poll(async()=>(await state()).tcp[2][3]).toBeGreaterThan(initial.tcp[2][3]+.001);
  await page.mouse.up();
  await expect(page.getByTestId('reachability-status')).toContainText('当前位置');
  expect(plans).toBe(0);
  await page.screenshot({path:path.join(output,'manual-light.png')});
  const valid=await state();
  await page.getByLabel('目标X',{exact:true}).fill('10000');
  await expect(page.getByTestId('reachability-status')).toContainText('未找到有效解');
  expect((await state()).q_deg).toEqual(valid.q_deg);
  await page.getByRole('button',{name:'取当前值'}).click();
  await page.getByLabel('显示路径预览').check();
  await expect(page.getByRole('button',{name:'预览路径',exact:true})).toBeVisible();
  await page.getByLabel('目标Y',{exact:true}).fill(String(valid.tcp[1][3]*1000+2));
  await expect(page.getByTestId('reachability-status')).toContainText('目标可达');
  expect((await state()).q_deg).toEqual(valid.q_deg);
  await page.getByRole('button',{name:'预览路径',exact:true}).click();
  await expect(page.locator('.feedback')).toContainText('预览通过');
  await expect(page.locator('.scene-stage')).toHaveAttribute('data-path-visible','true');
  await page.getByLabel('显示路径预览').uncheck();
  await expect(page.locator('.scene-stage')).toHaveAttribute('data-path-visible','false');
  await expect(page.getByRole('button',{name:'预览路径',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'记录当前姿态'}).click();
  await expect(page.locator('.step-list .step')).toHaveCount(1);
  await page.getByRole('button',{name:'关闭面板'}).click();
  await page.getByRole('button',{name:'示教模式',exact:true}).click();
  await expect(page.getByLabel('显示路径预览')).toBeChecked();
  await page.getByRole('button',{name:'自动控制',exact:true}).click();
  await expect(page.locator('.step-list .step')).toHaveCount(1);
  await page.getByRole('button',{name:'手动控制',exact:true}).click();
  await expect(page.getByLabel('显示路径预览')).not.toBeChecked();
  await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].setSize(960,720));
  await expect(page.getByRole('button',{name:'记录当前姿态'})).toBeInViewport();
  await expect(page.getByTitle('停止 Esc')).toBeInViewport();
  await page.screenshot({path:path.join(output,'manual-960.png')});
  expect(errors).toEqual([]);
 }finally{await app.close();}
});
