const {test,expect,_electron:electron} = require('@playwright/test');
const fs = require('node:fs');
const path = require('node:path');
test('桌面复用工作台：模型、控制、规划子进程、执行、文件与退出',async()=>{
  const output=path.resolve(__dirname,'../test-results/parity');
  fs.mkdirSync(output,{recursive:true});
  const env={...process.env,CYBERARM_TEST_USER_DATA:path.join(output,'user'),CYBERARM_TEST_DOWNLOAD_DIR:output};
  delete env.ELECTRON_RUN_AS_NODE;
  const packaged=process.env.CYBERARM_TEST_EXECUTABLE;
  const app=await electron.launch({...(packaged?{executablePath:packaged,args:[]}:{args:[path.resolve(__dirname,'..')]}),env});
  let url;
  try {
    const page=await app.firstWindow();
    if(packaged)await app.evaluate(({BrowserWindow},directory)=>{
      BrowserWindow.getAllWindows()[0].webContents.session.prependListener('will-download',(_,item)=>{
        item.setSaveDialogOptions=()=>{};
        item.setSavePath(directory+'/'+item.getFilename());
      });
    },output);
    await expect(page.locator('.connection')).toContainText('本地已连接',{timeout:60000});
    await expect(page.locator('.scene-caption')).not.toContainText('正在加载',{timeout:60000});
    await expect(page.locator('.scene-caption')).not.toContainText('失败');
    url=page.url();
    const api=async(route,body)=>page.evaluate(async({route,body})=>{
      const boot=await fetch('/api/bootstrap').then(r=>r.json());
      const response=await fetch('/api/'+route,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json','X-Session':boot.session,'X-Client':'test'},body:body===undefined?undefined:JSON.stringify(body)});
      return {status:response.status,data:await response.json()};
    },{route,body});
    await page.getByRole('button',{name:'关节',exact:true}).click();
    await page.getByTitle('目标增大 1 度').first().click();
    await page.getByRole('button',{name:'预览路径',exact:true}).click();
    await expect(page.locator('.feedback')).toContainText('预览通过',{timeout:90000});
    await page.getByRole('button',{name:'执行',exact:true}).click();
    await expect.poll(async()=> (await api('state')).data.q_deg[0],{timeout:20000}).toBeCloseTo(1,1);
    await page.getByTitle('停止 Esc').click();
    await page.getByRole('button',{name:'动作序列'}).click();
    await page.getByRole('button',{name:'保存当前目标'}).click();
    await page.getByRole('button',{name:'等待 1 秒'}).click();
    await page.getByRole('button',{name:'预览整组'}).click();
    await expect(page.locator('.feedback')).toContainText('预览通过',{timeout:90000});
    await page.getByRole('button',{name:'项目',exact:true}).click();
    await page.getByRole('button',{name:'导出项目'}).click();
    const project=path.join(output,'CyberArm-project.json');
    await expect.poll(()=>fs.existsSync(project)).toBeTruthy();
    expect(JSON.parse(fs.readFileSync(project)).steps.length).toBe(2);
    await page.locator('input[type=file]').setInputFiles(project);
    await expect(page.locator('.feedback')).toContainText('项目已载入');
    await page.getByRole('button',{name:'末端',exact:true}).click();
    await page.getByRole('button',{name:'取当前值'}).click();
    await page.getByRole('button',{name:'预览路径',exact:true}).click();
    await expect(page.locator('.feedback')).toContainText('预览通过',{timeout:90000});
    await page.getByLabel('末端直线运动 MoveL').check();
    await page.getByRole('button',{name:'预览路径',exact:true}).click();
    await expect(page.locator('.feedback')).toContainText('预览通过',{timeout:90000});
    await page.getByRole('button',{name:'场景',exact:true}).click();
    await page.getByRole('button',{name:'添加障碍物'}).click();
    await expect.poll(async()=> (await api('state')).data.obstacles.length).toBe(1);
    await page.locator('.drawer .step button').click();
    await expect.poll(async()=> (await api('state')).data.obstacles.length).toBe(0);
    const pausedProject=JSON.parse(fs.readFileSync(project));
    pausedProject.steps=[{kind:'wait',seconds:10}];
    const waiting=path.join(output,'waiting.json');fs.writeFileSync(waiting,JSON.stringify(pausedProject));
    await page.locator('input[type=file]').setInputFiles(waiting);
    await expect(page.locator('.feedback')).toContainText('项目已载入');
    await page.getByRole('button',{name:'动作序列'}).click();
    await page.getByRole('button',{name:'预览整组'}).click();
    await expect(page.locator('.feedback')).toContainText('预览通过',{timeout:90000});
    await page.getByRole('button',{name:'执行',exact:true}).click();
    await page.getByTitle('暂停',{exact:true}).click();
    await expect(page.locator('.status')).toHaveText('已暂停');
    await page.getByTitle('重新规划剩余动作').click();
    await expect(page.locator('.feedback')).toContainText('剩余动作已重新验证',{timeout:90000});
    await page.getByRole('button',{name:'执行',exact:true}).click();
    await page.keyboard.press('Escape');
    await expect(page.locator('.status')).toHaveText('就绪');
    const unreachable=await api('plan',{steps:[{kind:'cartesian',position_mm:[10000,10000,10000]}],speed:.7});
    expect(unreachable.status).toBe(422);
    const workspace=await api('workspace',{direction:null});
    expect(workspace.status).toBe(200);
    expect(workspace.data.points.length).toBeGreaterThan(0);
    for(const label of ['顶','前','侧','透视'])await page.getByRole('button',{name:label,exact:true}).click();
    await page.screenshot({path:path.join(output,'desktop.png')});
    const security=await page.evaluate(()=>({require:typeof window.require,process:typeof window.process}));
    expect(security).toEqual({require:'undefined',process:'undefined'});
  } finally {await app.close();}
  if(url)await expect.poll(async()=>{try{await fetch(new URL('/api/state',url),{signal:AbortSignal.timeout(1000)});return false;}catch{return true;}},{timeout:15000}).toBe(true);
});
