cmake_minimum_required(VERSION 3.20)
project(cyberarm_core LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 11)
add_library(cyberarm_core SHARED core.cpp collision.cpp)
if(MINGW)
  target_link_options(cyberarm_core PRIVATE -static -static-libgcc -static-libstdc++)
endif()
enable_testing()
add_executable(core_test core_test.cpp core.cpp)
add_test(NAME finite_and_interpolation COMMAND core_test)
